### ISSUE TITLE
Self-Selecting breakout rooms being added to Zoom Natively

### ISSUE THREAD

**Issue by MoralCode** [mrcromulent/ZoomBot#1]
Looks like zoom the ability for users to self-select the breakout room they are in will be added to the zoom apps in an update being released on Sept. 28th 2020.

Source: https://support.zoom.us/hc/en-us/articles/201361953

![Screenshot_20200925_194845](https://user-images.githubusercontent.com/17362949/94328550-5a024000-ff68-11ea-99e4-fce6d79c81d9.png)

**Comment by mrcromulent** [comment]
Thank you for letting me know, Adrian. I'll add this information to the top of the README.

**Comment by MoralCode** [comment]
whoops, turns out i messed up the date, i was looking at the most recent update at the top of the page. turns out this feature was actually already added in the September 21, 2020 version 5.3.0 (52651.0920)
